### ISSUE TITLE
AngularDoc keeps analysing

### ISSUE THREAD

**Issue by CumpsD** [AngularDoc/angulardoc.github.io#1]
I've installed AngularDoc VS Code extension, and when I click the AngularDoc item at the bottom, I login and it keeps on analysing. After closing VS Code and re-opening, I get the AngularDoc tab, with an empty Overview and no content.

The content of my angulardoc.json is:
```
{
  "repoId": "fbea66c1-b772-4a0d-abbc-c4fa5ba41b8c",
  "lastSync": 1481113468630,
  "directoryFilter": [
    "!typings",
    "!node_modules",
    "!.vscode"
  ],
  "fileFilter": [
    "**/!(*.*spec).ts"
  ]
}
```

Is there any documentation on this file? Maybe I need to help it out to find my application root?

**Comment by agiledigits** [comment]
Perhaps you can try setting "lastSync" to 0 to make the analyzer re-process all the files.

**Comment by CumpsD** [comment]
When I try that, it doesnt re-process all the files, it simply gives me an empty Overview screen :(

**Comment by agiledigits** [comment]
We have identified the problem and just released v1.1.0. Please try again and let us know what happens.

**Comment by mlc-mlapis** [comment]
I installed the latest version 1.1.0 (+ several times logout and login) but still having the same problem with "Analysing project ...".
Output views shows a massage:
`Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'access_token' of undefined`.
I do not know if it is important but I work behind a proxy server - its configuration is correct - I have full access to internet from VS Code, npm, ...

My angulardoc.json looks:
`{
  "repoId": "7bc64bad-.................................................",
  "directoryFilter": [
    "!typings",
    "!node_modules",
    "!.vscode"
  ],
  "fileFilter": [
    "**/!(*.*spec).ts"
  ],
  "lastSync": 0
}`

**Comment by agiledigits** [comment]
@mlc-mlapis Please try v1.2.0 and see if it fixed your issues.

**Comment by mlc-mlapis** [comment]
Thanks. It looks that the problem disappeared now.
