### ISSUE TITLE
Is it possible to log in directly through the site?

### ISSUE THREAD

**Issue by newaeonweb** [AngularDoc/angulardoc.github.io#10]
I have the vscode plugin but i aways got an error message when i'm trying to log in.

**Comment by roscopeeco** [comment]
UPDATE: The overview window looks as follows (i did close all child nodes the first time i viewed the section)...tried clicking on the play icon but nothing happens.

![image](https://user-images.githubusercontent.com/500203/30418069-aa8d9b26-9929-11e7-9c1d-e90143421076.png)

**Comment by agiledigits** [comment]
What was the error message?

**Comment by newaeonweb** [comment]
@agiledigits , sorry, i don't know happen but now it works! Thanks for your help.
