### ISSUE TITLE
can't login in

### ISSUE THREAD

**Issue by lizhuangs** [AngularDoc/angulardoc.github.io#12]
I can't receive the email and I try several times,so how can I login in？

**Comment by agiledigits** [comment]
Did you enter a valid email? If so, did you receive the activation email?

**Comment by lizhuangs** [comment]
yes.I tried another email,It failed too.my email is le.z@foxmail.com.can you do it manually.Tks

**Comment by lizhuangs** [comment]
yes.I tried another email,It failed too.
my email is le.z@foxmail.com.
can you do it manually.
Tks

**Comment by agiledigits** [comment]
The email was sent successfully. Could it be that it landed in the spam folder?

**Comment by lizhuangs** [comment]
I am sure there is nothing in the spam folder.I checked  it before and now.

**Comment by agiledigits** [comment]
We resent the email to le.z@foxmail.com. Please see if the third time is a charm.

**Comment by lizhuangs** [comment]
eeeeh,there is nothing.may be I will try live.com.Tks.

**Comment by lizhuangs** [comment]
ok.I used live.com and it successed.Tks
