### ISSUE TITLE
Stuck at "Initializing AngularDoc server"

### ISSUE THREAD

**Issue by gkaran** [AngularDoc/angulardoc.github.io#15]
Fresh installation of the plugin in vs code 1.18.1 on windows and when I run ngdoc it opens a blank tab.

The output channel keeps saying "Initializing AngularDoc server..." forever. 

Not sure what additional information I can provide but let me know and I will be happy to.

**Comment by agiledigits** [comment]
Yes we can reproduce it, too. Looks like vs code 1.18.1 broke our editor. We'll look into it. Thanks for reporting the issue!

**Comment by agiledigits** [comment]
@gkaran Please install v3.0.5 and let us know if it fixed the issue for you.

**Comment by gkaran** [comment]
Works great now. Thank you guys.

**Comment by dmaglio** [comment]
same issue for me with vs code v1.21.1 and angulardoc v3.0.5 (fedora 27 and windows 7)

**Comment by agiledigits** [comment]
@dmaglio We had an issue with the DB. Please try again.

**Comment by dmaglio** [comment]
@agiledigits if it can serve, I have noticed that it is not possible to login, in settings there are only username and email, no token
