### ISSUE TITLE
Contact form is not working

### ISSUE THREAD

**Issue by vojtechruz** [AngularDoc/angulardoc.github.io#16]
Your contact form is not working here, cannot submit the form:
https://angulardoc.github.io/contact/

In chrome  63.0.3239.84

Mixed Content: The page at 'https://angulardoc.github.io/contact/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://34.211.205.168/api/contact'. This request has been blocked; the content must be served over HTTPS.

**Comment by agiledigits** [comment]
Fixed. Please try again.
