### ISSUE TITLE
Cannot create an account

### ISSUE THREAD

**Issue by Saissaken** [AngularDoc/angulardoc.github.io#17]
When I try to create an account I'm getting: 

> Internal Server Error

Fresh install, fresh project with cli.
VSCode version: 1.19.1
OS: macOS Sierra 10.12.6

![image](https://user-images.githubusercontent.com/16063650/34695322-2e0baf26-f4a9-11e7-850d-d941275cb0fa.png)

**Comment by iwnow** [comment]
can't too

**Comment by agiledigits** [comment]
The login issue is fixed. Please try again and let us know if there's still a problem.

**Comment by GuillaumeUnice** [comment]
The issue seems to persist :s

**Comment by juanpablomorenomartin** [comment]
The issue seems to persist
