### ISSUE TITLE
Angular Coplit

### ISSUE THREAD

**Issue by tonogueira2** [AngularDoc/angulardoc.github.io#18]
Hi, my instalation of Angular Coplit 0.9.3 Win10 are error 

A JavaScript error occurred in the main process
![capturar](https://user-images.githubusercontent.com/19763503/38159890-9c618326-3480-11e8-9470-394bca2ceff3.PNG)

**Comment by agiledigits** [comment]
It was most likely due to a port conflict. Please download the latest Copilot and try again.
