### ISSUE TITLE
Project is null

### ISSUE THREAD

**Issue by djbreen7** [AngularDoc/angulardoc.github.io#20]
After importing a loal project, I'm unable to view the project. I receive the error: The project is null.

![image](https://user-images.githubusercontent.com/13296622/39198185-a95ef4ce-47a3-11e8-8351-99f7568ef04c.png)

**Comment by agiledigits** [comment]
Could it be that your project is an AngularJS one with TypeScript source code?

**Comment by djbreen7** [comment]
Nope. It's Angular 5.2:
https://github.com/ToucanTesting/ToucanTesting.Client

**Comment by agiledigits** [comment]
Apparently the regex in this snippet tripped up the AST parser:
`const jwtConf = {
  config: {
    tokenGetter: tokenGetter,
    whitelistedDomains: [
      /^null$/
    ],
    throwNoTokenError: true
  }
};`

As a result, the NgModule info could not be obtained from AppModule. Unfortunately it's in one of the angular packages and we don't have a workaround yet. You might want to move this snippet to a separate file to unblock the project analysis.

**Comment by dapperdandev** [comment]
Okay. I'll import it from another file and see if that solves it. Thanks for the follow up.
