### ISSUE TITLE
ENOENT: no such file or directory, stat 'C:\c:\Users\..'

### ISSUE THREAD

**Issue by apumex** [AngularDoc/angulardoc.github.io#23]
I am running AngularDoc 6.0.2 VSCode 1.24.1

Anytime I try to execute any command I get this error.
ENOENT: no such file or directory, stat 'C:\c:\Users\

**Comment by agiledigits** [comment]
@apumex Could you try v6.0.3 in which we made a fix for Windows.

**Comment by apumex** [comment]
Thanks. Just tried. It did work.

Thanks
