### ISSUE TITLE
Error: Server response code is 404

### ISSUE THREAD

**Issue by andresrl** [AngularDoc/angulardoc.github.io#3]
Hello, I'm having an issue that gives me an error 404 when AngularDoc extension is active.
I have disabled all extensions except AngularDoc and the problem happens. But if AngularDoc is inactive there's no problem.

My problem happens when Node is running and I change a .ts file.
Then a incremental compilation happens: _(12:12:02 - File change detected. Starting incremental compilation...)_

And before that the **"Error: Server response code is 404"** happens in the messages of VSCode

![angulardoc 404 problem](https://cloud.githubusercontent.com/assets/22559010/23549495/d2aa5f7e-000c-11e7-992b-55f84cb7bb40.png)

I have try to Logout and Login in AngularDoc, but the problem persists.

You can view it also in another user that I think happens the same:
https://github.com/Microsoft/vscode/issues/21535#event-985228326

**Comment by agiledigits** [comment]
This message "File change detected. Starting incremental compilation..." was not from AngularDoc, but the "Error: Server response code is 404" message was. Could you check what messages were printed in the Output channel "AngularDoc"?

**Comment by andresrl** [comment]
Sorry @agiledigits for the misunderstanding, the 'File change detected...' message it's from TSC, not from AngularDoc.

Anyway there were no messages in the Output channel of "AngularDoc"

Also, I've tried in a different computer (with my settings synced) and the error persists when AngularDoc is active

**Comment by agiledigits** [comment]
@andresrl We couldn't reproduce the exact error message but spotted a similar one that occurred for renamed/deleted files. Please try v2.0.2 that we just published and let us know if it fixed your issue.

**Comment by andresrl** [comment]
Thanks! @agiledigits , it's seems that has been solved.
Now there's no errors.
