### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by ChuckJonas** [AngularDoc/angulardoc.github.io#39]
If I try to run `open file`.  I just get `command 'copilot.explorer.open' not found`.

Same with refresh.

Also, when I try to load the application explorer it just says 

>There is no data provider registered that can provide view data.

**Comment by ChuckJonas** [comment]
I got here from the https://marketplace.visualstudio.com/items?itemName=Metatype.copilot-vscode extension... not sure why...

**Comment by agiledigits** [comment]
Which project did you have? How did you run the "open file" command when there's no data in the tree view?

**Comment by ChuckJonas** [comment]
it's a typescript react project.  I ran `cmd-shift p` -> `co-pilot: open file`.  The command shows up regardless of the vscode context

**Comment by FlavioMH** [comment]
The same for me.
I am usign VSCode Insiders 1.34.0 on Windows.
Even if I try to refresh _Copilot application explorer_ it says: `command 'copilot.explorer.refresh' not found`

**Comment by c0h1b4** [comment]
Same here. VueJS project.

**Comment by knlambert** [comment]
Same here.

![image](https://user-images.githubusercontent.com/16439060/56378962-91e64f00-61dc-11e9-857a-48c0af682776.png)

**Settings.json :** 

`
{
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Dracula",
    "window.zoomLevel": -1,
    "editor.minimap.enabled": false,
    "angulardoc.project_root": "./client/"
}
`

**My tree :**

![image](https://user-images.githubusercontent.com/16439060/56378939-8135d900-61dc-11e9-9a46-6908821eddb2.png)

**Comment by agiledigits** [comment]
@knlambert Could you do a Skype session with us right now to debug this issue?

**Comment by agiledigits** [comment]
@knlambert @ChuckJonas @FlavioMH Please try v1.0.2 and see if you still have problems.

**Comment by agiledigits** [comment]
This is most likely due to a failed analyzer download. Starting from v1.1.0 an error message will be shown on the status bar to alert the users about that.

**Comment by papiermache** [comment]
What closed this? Just installed Copilot, nothing works, errors:  "command copilot.explorere.refresh not found" and "copilot server (e || []).filter is not a function" and "copilot: pen home page resulted in an error".
