### ISSUE TITLE
Excluding Third Party components from dependency graph

### ISSUE THREAD

**Issue by ChuckJonas** [AngularDoc/angulardoc.github.io#41]
I'm using the antd react component library in my application.  When I open the component dependency graph, it includes all of these components, which makes it so cluttered, it's essentially useless.

Is there some way to exclude entire modules from the analysis or display?

FYI, I would attach a screensot, but at the moment I'm just getting a "There is no data provider registered that can provide view data" error....

**Comment by agiledigits** [comment]
You can click on the legend to show or hide an entire module.
