### ISSUE TITLE
Not sure about AngularDoc view hierarchy.

### ISSUE THREAD

**Issue by chriscurnow** [AngularDoc/angulardoc.github.io#42]
When I open my application in the AngularDoc Application Explorer, I see all the modules listed alphabetically.

This is very unhelpful as I would like to see the modules listed hierarchically.

For instance in my app `NewContractModule` is a submodule of `ContractModule` but they are very widely separated in the Application Explorer.

I would like to see `NewContractModule` listed underneath 'ContractModule`.

**Comment by agiledigits** [comment]
This is implemented in Copilot v1.2.2.
