### ISSUE TITLE
Co-pilot keeps crashing

### ISSUE THREAD

**Issue by chriscurnow** [AngularDoc/angulardoc.github.io#43]
I just tried to open my app in Co-pilot.

I selected the app in Co-pilot, it came up with the 'Analysing' progress bar and whirred away for about 20 seconds then Co-pilot showed as 'Not Responding' in the 'Force Quit Applications'  dialog. About 20 seconds later, Co-pilot disappeared from this dialog as well.

**Comment by agiledigits** [comment]
@chriscurnow Did you mean Copilot extension in VS Code or Copilot the desktop app?

**Comment by chriscurnow** [comment]
@agiledigits this is the process I followed:

- from VS Code, select `AngularDoc` from the toolbar at the bottom of the screen
- select `Open in Angular Copilot`
- the Angular Copilot app opens
- I click `local` in the panel on the left
- It shows the path to my project
- I click on the path
   - sometimes it crashes at this point
   - sometimes it goes on to analysing and then crashes

**Comment by agiledigits** [comment]
Please use the Copilot extension (https://marketplace.visualstudio.com/items?itemName=Metatype.copilot-vscode) for your angular projects. The AngularDoc extension and Copilot desktop app are used in AngularJS migration.

**Comment by chriscurnow** [comment]
OK, I just did that and it is analysing at the moment. So far so good.

My question is though, how would I have know to install the extension? I can't find any reference to it on your website or other documentation.

Wouldn't it be a good idea to put a note about this on the AngularDoc extension page in the marketplace?

It looks like you have some absolutely brilliant products but there is so much information that is just not accessible.

I would be prepared to pay for this extension if it really does what it says it does.

I went to your web page `angulardoc.io` and it doesn't say anything about this at all. It just talks about 'Team Service'. This looks like a great product and would have paid the $99 subscription for it if I could have. It just wouldn't let me.

I really want to support you, but I think you have to make it a bit easier.

I really appreciate your prompt responses.
