### ISSUE TITLE
Found .angulardoc.json file in my newly generated Angular project

### ISSUE THREAD

**Issue by orimdominic** [AngularDoc/angulardoc.github.io#46]
In response to [this tweet](https://twitter.com/angulardocio/status/806234031423504384), I am filing this issue.

I have been generating new Angular projects before now and I have never seen a `.angulardoc.json` file in the folder in which I generated my Angular project.

Recently, I upgraded my Angular Cli to the following 

```
Angular CLI: 9.0.1
Node: 12.13.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

and now when I generate a new project, I see a `.angulardoc.json` file in the same folder with the folder in which I my project was generated.

The file contains an object with two keys: `repoId` which has the value of an auto-generated key, and `lastSync` which has a value of `0` for now.

What is the purpose of this file? Is this a VSCode thing or an Angular thing?
Could you also please answer a [question I posted on Stackoverflow](https://stackoverflow.com/questions/60144403/what-is-the-purpose-of-the-angulardoc-json-file-in-an-angular-project) on this issue?

Thanks

**Comment by danvic712** [comment]
I have already seen this file when I run my new created project, did you installed a vs code plugin named [AngularDoc for Visual Studio Code](https://angulardoc.github.io/#/)? I think this file may generated by this plugin, when I uninstall it, it's disappears.
![image](https://user-images.githubusercontent.com/32116018/74236075-5ab4d180-4d0b-11ea-8e84-1f3d4554318d.png)

**Comment by orimdominic** [comment]
Thanks. I checked my extensions for it and found that I do not have the extension installed. I have a colleague (@taiwosunday99) who also has the same issue. 
In fact, I saw it on his computer first and when I created a new project, I saw it on mine too. He also doesn't have the extension installed.

![angulardoc](https://user-images.githubusercontent.com/37955249/74293792-1c83d600-4d3c-11ea-9b57-f99b63d59c39.png)

**Comment by agiledigits** [comment]
This file was generated from AngularDoc's VSCode extension. Its purpose is to uniquely identify this repo when multiple developers are using the AngularDoc service. It doesn't do anything if it's a standalone project (i.e. the AngularDoc analyzer runs locally).

**Comment by orimdominic** [comment]
I'm closing the issue because I have come to know what the purpose of the file is, but I still don't understand how it was generated when I don't even have the extension installed.

Thanks.

**Comment by Jopie64** [comment]
Should it be added to source control? (Git)

**Comment by orimdominic** [comment]
@Jopie64 I think from what @agiledigits [has said](https://github.com/AngularDoc/angulardoc.github.io/issues/46#issuecomment-585069843), if it is a project being worked on by multiple developers, it should be.
