### ISSUE TITLE
AngularDoc hangs on Analyzing project

### ISSUE THREAD

**Issue by valkanov** [AngularDoc/angulardoc.github.io#7]
When click on AngularDoc icon, it starts to analyze the project and it lasts forever.
When I close the tab and open it again, it does not analyze anymore, but shows nothing.

![capture](https://cloud.githubusercontent.com/assets/5782506/25891504/fbceb222-3579-11e7-9216-31afd4999466.PNG)
![capture1](https://cloud.githubusercontent.com/assets/5782506/25891505/fbd0ef6a-3579-11e7-9238-ef9a155b919a.PNG)

Visual Studio Code
Version 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
Date 2017-05-04T21:26:50.689Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by ArnoutPullen** [comment]
Same

**Comment by agiledigits** [comment]
What was showing in the output channel "AngularDoc"? Does the root directory have the "package.json" file?

**Comment by agiledigits** [comment]
We have published v2.2.0 which has a new "refresh" button to allow you to manually trigger the analyzer. Please try it and let us know what happens. DO make sure that "package.json" is in the project root.
