### ISSUE TITLE
AngularDoc no work after installed

### ISSUE THREAD

**Issue by aguedesp** [AngularDoc/angulardoc.github.io#9]
After installing AngularDoc, the only visible change is in the context menu where the commands appear, but when choosing a command, nothing happens, the field to type the name of the component does not appear.
The status bar item "AngularDoc" (located at the bottom left) also does not appear.
E ngdoc in the command palette (cmd-shift-p) results in 'ngdoc' command not found.

Can you help me?

**Comment by brunoksi** [comment]
I have the same problem, quoted above, please can anyone help?

**Comment by mateothegreat** [comment]
Happening with code & code-insiders on both linux & windows..
```
code --list-extensions
AngularDoc.angulardoc-vscode
```

`code-insiders --version
1.15.0-insider
56a5bf1724f3b882e149a3e7a24e6105a7b837c2
`
>[38190:0714/055321.351141:INFO:CONSOLE(28)] "command 'ngdoc' not found", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (28)

`code --version
1.14.1
2648980a697a4c8fb5777dcfb2ab110cec8a2f58
`

>[46000:0714/060312.864887:INFO:CONSOLE(29)] "Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at /home/yomateod/.vscode/extensions/AngularDoc.angulardoc-vscode-2.2.2/build/js/extension.js:2:10147
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:41973)
    at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:45538)
    at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:47366)
    at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:46807)
    at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188642)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189725)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)

**Comment by agiledigits** [comment]
It seems that the extension has not been activated. The most likely cause is that there's no package.json file in the project root directory.

**Comment by dakipro** [comment]
same here as the poster aguedesp mentioned. I do have package.json in the root directory.
Is there some other step needed for it to work, or is it just install and play?

**Comment by maliksahil** [comment]
Same here - VSCode 1.15.1, I see the menu items, but I do not see an option on the bottom right. 
If I try running ngdoc, it says 'Command ngdoc was not found'

**Comment by mlc-mlapis** [comment]
Same here - VSCode 1.15.1, AngularDoc 3.0.1.

> If I try running ngdoc, it says 'Command ngdoc was not found'.

**Comment by agiledigits** [comment]
@mlc-mlapis Could you post your package.json file here (at least the dependencies part)?

**Comment by mlc-mlapis** [comment]
@agiledigits ... here it is. But I think that the problem is something else. What I don't understand is the fact that `ngdoc` could not be found at all. Angular CLI 1.3.2 is installed globally but the project itself is not developed under it.

```
{
	"name": "angular-dynamicmodules",
	"version": "0.4.39",
	"private": true,
	"license": "",
	"scripts": {
		"tsc": "./node_modules/.bin/tsc --outDir ./app",
		"tsc:w": "./node_modules/.bin/tsc -w --outDir ./app",
		"i18n": "./node_modules/.bin/ng-xi18n -p tsconfig.i18n.json --i18nFormat xlf"
	},
	"dependencies": {
		"systemjs": "0.20.18",
		"systemjs-plugin-text": "0.0.11",
		"systemjs-plugin-json": "0.3.0",
		"core-js": "2.5.1",
		"reflect-metadata": "0.1.10",
		"rxjs": "5.4.3",
		"zone.js": "0.8.16",
		"@angular/core": "4.3.6",
		"@angular/common": "4.3.6",
		"@angular/compiler": "4.3.6",
		"@angular/compiler-cli": "4.3.6",
		"@angular/platform-server": "4.3.6",
		"@angular/platform-browser": "4.3.6",
		"@angular/platform-browser-dynamic": "4.3.6",
		"@angular/platform-webworker": "4.3.6",
		"@angular/platform-webworker-dynamic": "4.3.6",
		"@angular/language-service": "4.3.6",
		"@angular/http": "4.3.6",
		"@angular/forms": "4.3.6",
		"@angular/router": "4.3.6",
		"@angular/animations": "4.3.6",
		"@angular/service-worker": "1.0.0-beta.16",
		"@ngrx/core": "1.2.0",
		"@ngrx/store": "4.0.3",
		"primeng": "4.1.3",
		"raven-js": "3.17.0",
		"runtime-type-checks": "0.0.4"
	},
	"devDependencies": {
		"@types/jasmine": "2.5.54",
		"@types/node": "8.0.26",
		"codelyzer": "3.1.2",
		"del": "3.0.0",
		"express": "4.15.4",
		"gulp": "3.9.1",
		"gulp-live-server": "0.0.31",
		"gulp-server-livereload": "1.9.2",
		"gulp-sourcemaps": "2.6.1",
		"gulp-tslint": "8.1.2",
		"gulp-typescript": "3.2.2",
		"multer": "1.3.0",
		"nodemon": "1.12.0",
		"npm-run-all": "4.1.1",
		"path": "0.12.7",
		"request": "2.81.0",
		"rollup": "0.49.2",
		"systemjs-builder": "0.16.10",
		"tslint": "5.7.0",
		"typescript": "2.4.2",
		"uglify-js": "3.0.28"
	}
}
```

**Comment by agiledigits** [comment]
@mlc-mlapis We did find an extension activation problem on Windows. We are working on a fix.

**Comment by mlc-mlapis** [comment]
@agiledigits ... great news ... I am looking for ... 💚

**Comment by agiledigits** [comment]
@mlc-mlapis Please try v3.0.2.

**Comment by mlc-mlapis** [comment]
@agiledigits I can confirm that version 3.0.2 solved the problem with the extension activation problem on Windows. Everything works as expected now.

Thanks a lot.

**Comment by himan20** [comment]
Getting an error "Unable to open 'AngularDoc': Cannot read property 'access_token' of undefined."
Tried to activate the extension by left corner button and also through ngdoc command palette option.

Tried on the VSCode Version 1.22.2 and VSCode Insider Version 1.23.0-insider

**Comment by danielpiedra** [comment]
Having the same issue on macOs High Sierra, vsCode 1.24.1.

Any command will be `not found` and  Application explorer or Outline are Empty, refreshing throws error as well.

Anyone has the same?

**Comment by danielpiedra** [comment]
For posterity, my issue seemed to be related with how my angular dependencies were managed. Because in our project we have developed our own cli around angular and have transcluded deps => ```@xx/angular: 1.0.0``` where we manage angular related deps, we don't have them right in the app package.json but they live in their own repo. I did an npm install with the deps copied locally and it all worked just fine.

@agiledigits: not entirely sure how the extension works but perhaps it could look at ```package-lock.json``` for those dependencies?

**Comment by agiledigits** [comment]
@danielpiedra I might be mistaken but I don't think package-lock.json plays any role in the Angular compiler, unless there's a way for our extension to call your CLI instead.

**Comment by danielpiedra** [comment]
@agiledigits correct me if I'm wrong, but I am assuming the extension looks at the ```package.json``` to find @angular deps? in that case for a project like ours it won't find them because they are installed via ```@xx/angular``` package.

**Comment by agiledigits** [comment]
@danielpiedra Please try v6.0.3 in which we made a fix to also look in node_modules for angular libs.

**Comment by ramden** [comment]
On Windows 10 it does not work on any project.

I tried opening several projects, all I get in application explorer a empty folder .

After clicking on refresh button up right it spins for a while but then nothing happens

@angular/cli version installed (globally) - 1.5.0

```
Angular CLI: 1.5.0
Node: 8.9.4
OS: win32 x64
Angular: 5.0.5
```

Extension version installed 6.0.5
Visual Studio Code 1.23.1

**Comment by agiledigits** [comment]
@ramden Angular Explorer only works with v6.0 and your project is still v5 (angular-cli being v1.5).
